# Generated by Django 3.2.4 on 2021-06-29 15:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisoryMember',
            fields=[
                ('flag', models.IntegerField(default=0)),
                ('number', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=25, null=True)),
                ('office', models.CharField(max_length=75, null=True)),
                ('name', models.CharField(max_length=25, null=True)),
                ('mail', models.EmailField(max_length=30, null=True)),
                ('text', models.CharField(max_length=260, null=True)),
                ('frg1', models.CharField(max_length=260, null=True)),
                ('frg2', models.CharField(max_length=260, null=True)),
                ('frg3', models.CharField(max_length=260, null=True)),
                ('frg4', models.CharField(max_length=260, null=True)),
                ('anlagen', models.CharField(max_length=260, null=True)),
                ('aenderung', models.CharField(max_length=260, null=True)),
                ('mehrheit', models.CharField(max_length=25, null=True)),
                ('beschluss', models.CharField(max_length=25, null=True)),
                ('beschlusstext', models.CharField(max_length=25, null=True)),
                ('beschlussgrund', models.CharField(max_length=25, null=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Conduct',
            fields=[
                ('flag', models.IntegerField(default=0)),
                ('number', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=25, null=True)),
                ('office', models.CharField(max_length=75, null=True)),
                ('name', models.CharField(max_length=25, null=True)),
                ('mail', models.EmailField(max_length=30, null=True)),
                ('text', models.CharField(max_length=260, null=True)),
                ('reason', models.CharField(max_length=260, null=True)),
                ('suggestion', models.CharField(max_length=260, null=True)),
                ('anlagen', models.CharField(max_length=260, null=True)),
                ('aenderung', models.CharField(max_length=260, null=True)),
                ('mehrheit', models.CharField(max_length=25, null=True)),
                ('beschluss', models.CharField(max_length=25, null=True)),
                ('beschlusstext', models.CharField(max_length=25, null=True)),
                ('beschlussgrund', models.CharField(max_length=25, null=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('flag', models.IntegerField(default=0)),
                ('number', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=25, null=True)),
                ('office', models.CharField(max_length=75, null=True)),
                ('name', models.CharField(max_length=25, null=True)),
                ('mail', models.EmailField(max_length=30, null=True)),
                ('text', models.CharField(max_length=260, null=True)),
                ('reason', models.CharField(max_length=260, null=True)),
                ('budget', models.CharField(max_length=260, null=True)),
                ('suggestion', models.CharField(max_length=260, null=True)),
                ('anlagen', models.CharField(max_length=260, null=True)),
                ('aenderung', models.CharField(max_length=260, null=True)),
                ('mehrheit', models.CharField(max_length=25, null=True)),
                ('beschluss', models.CharField(max_length=25, null=True)),
                ('beschlusstext', models.CharField(max_length=25, null=True)),
                ('beschlussgrund', models.CharField(max_length=25, null=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('flag', models.IntegerField(default=0)),
                ('number', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=25, null=True)),
                ('office', models.CharField(max_length=75, null=True)),
                ('name', models.CharField(max_length=25, null=True)),
                ('mail', models.EmailField(max_length=30, null=True)),
                ('text', models.CharField(max_length=260, null=True)),
                ('frg1', models.CharField(max_length=260, null=True)),
                ('frg2', models.CharField(max_length=260, null=True)),
                ('frg3', models.CharField(max_length=260, null=True)),
                ('frg4', models.CharField(max_length=260, null=True)),
                ('frg_spez_1', models.CharField(max_length=260, null=True)),
                ('frg_spez_2', models.CharField(max_length=260, null=True)),
                ('frg_spez_3', models.CharField(max_length=260, null=True)),
                ('anlagen', models.CharField(max_length=260, null=True)),
                ('aenderung', models.CharField(max_length=260, null=True)),
                ('mehrheit', models.CharField(max_length=25, null=True)),
                ('beschluss', models.CharField(max_length=25, null=True)),
                ('beschlusstext', models.CharField(max_length=25, null=True)),
                ('beschlussgrund', models.CharField(max_length=25, null=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Universall',
            fields=[
                ('flag', models.IntegerField(default=0)),
                ('number', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=25, null=True)),
                ('office', models.CharField(max_length=75, null=True)),
                ('name', models.CharField(max_length=25, null=True)),
                ('mail', models.EmailField(max_length=30, null=True)),
                ('text', models.CharField(max_length=260, null=True)),
                ('reason', models.CharField(max_length=260, null=True)),
                ('suggestion', models.CharField(max_length=260, null=True)),
                ('anlagen', models.CharField(max_length=260, null=True)),
                ('aenderung', models.CharField(max_length=260, null=True)),
                ('mehrheit', models.CharField(max_length=25, null=True)),
                ('beschluss', models.CharField(max_length=25, null=True)),
                ('beschlusstext', models.CharField(max_length=25, null=True)),
                ('beschlussgrund', models.CharField(max_length=25, null=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
