# Generated by Django 3.2.4 on 2021-07-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Antragsverwaltungstool', '0002_auto_20210630_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisorymember',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='conduct',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='finance',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='universall',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
