# Generated by Django 3.2.4 on 2021-07-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Antragsverwaltungstool', '0003_auto_20210701_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisorymember',
            name='beschluss',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='advisorymember',
            name='beschlussgrund',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='advisorymember',
            name='beschlusstext',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='conduct',
            name='beschluss',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='conduct',
            name='beschlussgrund',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='conduct',
            name='beschlusstext',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='finance',
            name='beschluss',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='finance',
            name='beschlussgrund',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='finance',
            name='beschlusstext',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='beschluss',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='beschlussgrund',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='beschlusstext',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='universall',
            name='beschluss',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='universall',
            name='beschlussgrund',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='universall',
            name='beschlusstext',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
