# Generated by Django 4.0.1 on 2022-06-20 18:34

import Antragsverwaltungstool.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Antragsverwaltungstool', '0004_auto_20210701_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisorymember',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conduct',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='finance',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='position',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='universall',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='advisorymember',
            name='anlagen',
            field=models.FileField(null=True, upload_to=Antragsverwaltungstool.models.upload_attachment),
        ),
        migrations.AlterField(
            model_name='conduct',
            name='anlagen',
            field=models.FileField(null=True, upload_to=Antragsverwaltungstool.models.upload_attachment),
        ),
        migrations.AlterField(
            model_name='finance',
            name='anlagen',
            field=models.FileField(null=True, upload_to=Antragsverwaltungstool.models.upload_attachment),
        ),
        migrations.AlterField(
            model_name='position',
            name='anlagen',
            field=models.FileField(null=True, upload_to=Antragsverwaltungstool.models.upload_attachment),
        ),
        migrations.AlterField(
            model_name='universall',
            name='anlagen',
            field=models.FileField(null=True, upload_to=Antragsverwaltungstool.models.upload_attachment),
        ),
    ]
