version: '3.6'

services:
  webserver:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/Antragsverwaltungstool
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test

volumes:
  postgres_data: