version: '3.6'

services:
  webserver:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/Antragsverwaltungstool
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  
  # databse:
  #   image: postgres:13.0-alpine
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/

    depends_on:
      - db
  db:
    image: mysql
    volumes:
      - mysql_data: /var/lib/mysql/data/
    environment:
      -   MYSQL_USER=Testuser
      -   MYSQL_PASSWORD=Testpw
      -   MYSQL_DB=Testuser_dev

#volumes:
#  postgres_data: