version: '3.6'

services:
  webserver:
    build: ./
    command: bash -c "python3 manage.py wait_for_database && python3 manage.py migrate && python manage.py runserver 0.0.0.0:"
    volumes:
      - ./:/usr/src/Antragsverwaltungstool
    ports:
      - 5432:5432
    env_file:
      - ./.env.dev
    container_name: django_webserver
  
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=abv
      - POSTGRES_PASSWORD=abv
      - POSTGRES_DB=abv
    container_name: postgres_database

volumes:
  postgres_data: