version: '3.6'

services:
  webserver:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/Antragsverwaltungstool
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  
  # databse:
  #   image: postgres:13.0-alpine
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/